---
# MongoDB Secret for credentials
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  username: cm9vdA==     # base64 for 'root'
  password: cm9vdA==         # base64 for 'root'
#---
# Static PersistentVolume
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: mongodb-pv
#spec:
#  capacity:
#    storage: 1Gi
#  accessModes:
#    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Retain
#  hostPath:
#    path: /data/mongodb-0   # Ensure this directory exists or will be created on Minikube
#    type: DirectoryOrCreate
---
# StorageClass
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-storage
provisioner: docker.io/hostpath
volumeBindingMode: Immediate
---
# PersistentVolumeClaim for mongodb-pv
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  #volumeName: mongodb-pv
  #storageClassName: ""  # No dynamic provisioning
  storageClassName: standard
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: "mongodb-headless"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc
---
# Headless Service for StatefulSet (Stable Network ID)
apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
spec:
  clusterIP: None  # Headless
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
---
# Service to expose MongoDB via ClusterIP (optional)
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017